package crowdsec

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

// BouncerSync implements a lightweight CrowdSec bouncer that generates nginx
// geo blocklist rules. It polls CrowdSec decisions and writes a geo config
// file that nginx uses to block banned IPs at the HTTP level.
//
// This is used in Docker mode where the iptables-based firewall bouncer
// isn't practical (would need NET_ADMIN + host networking).
type BouncerSync struct {
	manager            *Manager
	confPath           string // nginx conf.d directory
	testFn             func() error
	reloadFn           func() error
	stopCh             chan struct{}
	wg                 sync.WaitGroup
	lastHash           string
	bouncerRegistered  bool
}

// NewBouncerSync creates a new bouncer sync instance.
// testFn and reloadFn are called to test and reload nginx after updating the blocklist.
func NewBouncerSync(manager *Manager, confPath string, testFn, reloadFn func() error) *BouncerSync {
	return &BouncerSync{
		manager:  manager,
		confPath: confPath,
		testFn:   testFn,
		reloadFn: reloadFn,
		stopCh:   make(chan struct{}),
	}
}

// Start registers the bouncer with CrowdSec, performs an initial sync,
// and starts the background polling loop.
func (b *BouncerSync) Start() {
	b.ensureBouncer()
	b.writeBlocklist() // ensure file exists even if empty

	b.wg.Add(1)
	go b.loop()
	log.Println("[crowdsec-bouncer] Started nginx blocklist sync")
}

// Stop gracefully shuts down the bouncer sync loop.
func (b *BouncerSync) Stop() {
	close(b.stopCh)
	b.wg.Wait()
	log.Println("[crowdsec-bouncer] Stopped nginx blocklist sync")
}

func (b *BouncerSync) loop() {
	defer b.wg.Done()
	ticker := time.NewTicker(15 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			if !b.bouncerRegistered {
				b.ensureBouncer()
			}
			b.writeBlocklist()
		case <-b.stopCh:
			return
		}
	}
}

// ensureBouncer registers a bouncer with CrowdSec if one doesn't already exist.
func (b *BouncerSync) ensureBouncer() {
	if !b.manager.IsRunning() {
		return
	}

	bouncers, err := b.manager.ListBouncers()
	if err == nil {
		for _, bouncer := range bouncers {
			if bouncer.Name == "proxera-nginx-bouncer" {
				log.Println("[crowdsec-bouncer] Bouncer already registered")
				b.bouncerRegistered = true
				return
			}
		}
	}

	_, err = b.manager.runCscliCmd("bouncers", "add", "proxera-nginx-bouncer", "-o", "raw")
	if err != nil {
		log.Printf("[crowdsec-bouncer] Warning: failed to register bouncer: %v", err)
	} else {
		log.Println("[crowdsec-bouncer] Registered proxera-nginx-bouncer with CrowdSec")
		b.bouncerRegistered = true
	}
}

// writeBlocklist polls CrowdSec decisions and writes the nginx geo blocklist.
func (b *BouncerSync) writeBlocklist() {
	if !b.manager.IsRunning() {
		return
	}

	decisions, err := b.manager.ListDecisions()
	if err != nil {
		log.Printf("[crowdsec-bouncer] Failed to list decisions: %v", err)
		return
	}

	// Collect unique IPs/ranges with ban action
	// CrowdSec uses "type" field for action type (ban/captcha/etc)
	ips := make(map[string]bool)
	for _, d := range decisions {
		action := d.Type
		if action == "" {
			action = d.Action
		}
		if action == "ban" && (d.Scope == "Ip" || d.Scope == "Range") && d.Value != "" {
			ips[d.Value] = true
		}
	}

	// Sort for deterministic output
	sorted := make([]string, 0, len(ips))
	for ip := range ips {
		sorted = append(sorted, ip)
	}
	sort.Strings(sorted)

	// Generate geo block config
	var sb strings.Builder
	sb.WriteString("# CrowdSec blocklist - auto-generated by Proxera\n")
	sb.WriteString("# Do not edit manually - updated every 15 seconds\n\n")
	sb.WriteString("geo $crowdsec_blocklist {\n")
	sb.WriteString("    default 0;\n")
	for _, ip := range sorted {
		sb.WriteString(fmt.Sprintf("    %s 1;\n", ip))
	}
	sb.WriteString("}\n")

	content := sb.String()

	// Check if content changed
	hash := sha256.Sum256([]byte(content))
	newHash := hex.EncodeToString(hash[:])
	if newHash == b.lastHash {
		return
	}

	// Write config
	confFile := filepath.Join(b.confPath, "crowdsec_blocklist.conf")
	if err := os.WriteFile(confFile, []byte(content), 0644); err != nil {
		log.Printf("[crowdsec-bouncer] Failed to write blocklist: %v", err)
		return
	}

	b.lastHash = newHash
	log.Printf("[crowdsec-bouncer] Updated blocklist: %d IPs banned", len(sorted))

	// Test and reload nginx
	if b.testFn != nil {
		if err := b.testFn(); err != nil {
			log.Printf("[crowdsec-bouncer] Nginx test failed after blocklist update: %v", err)
			return
		}
	}
	if b.reloadFn != nil {
		if err := b.reloadFn(); err != nil {
			log.Printf("[crowdsec-bouncer] Failed to reload nginx: %v", err)
		}
	}
}
