package deploy

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

const (
	cloudflareConfPath = "/etc/nginx/conf.d/cloudflare-real-ip.conf"
	cloudflareMaxAge   = 7 * 24 * time.Hour // Refresh after 7 days

	cloudflareIPv4URL = "https://www.cloudflare.com/ips-v4"
	cloudflareIPv6URL = "https://www.cloudflare.com/ips-v6"

	// Last date the fallback IP lists below were verified against Cloudflare's published ranges.
	// Update these lists periodically from https://www.cloudflare.com/ips/
	fallbackLastUpdated = "2026-02-11"
)

var fallbackIPv4 = []string{
	"173.245.48.0/20",
	"103.21.244.0/22",
	"103.22.200.0/22",
	"103.31.4.0/22",
	"141.101.64.0/18",
	"108.162.192.0/18",
	"190.93.240.0/20",
	"188.114.96.0/20",
	"197.234.240.0/22",
	"198.41.128.0/17",
	"162.158.0.0/15",
	"104.16.0.0/13",
	"104.24.0.0/14",
	"172.64.0.0/13",
	"131.0.72.0/22",
}

var fallbackIPv6 = []string{
	"2400:cb00::/32",
	"2606:4700::/32",
	"2803:f800::/32",
	"2405:b500::/32",
	"2405:8100::/32",
	"2a06:98c0::/29",
	"2c0f:f248::/32",
}

// EnsureCloudflareRealIP ensures the Cloudflare real IP restoration config exists.
// Skips if the file exists and is less than 7 days old.
func (d *Deployer) EnsureCloudflareRealIP() error {
	// Check if file exists and is recent enough
	info, err := os.Stat(cloudflareConfPath)
	if err == nil && time.Since(info.ModTime()) < cloudflareMaxAge {
		return nil
	}

	// Fetch IP ranges from Cloudflare
	ipv4, err4 := fetchIPRanges(cloudflareIPv4URL)
	ipv6, err6 := fetchIPRanges(cloudflareIPv6URL)

	// Fall back to hardcoded ranges if fetch fails
	if err4 != nil || len(ipv4) == 0 {
		log.Printf("Warning: failed to fetch Cloudflare IPv4 ranges: %v, using fallback (last updated %s)", err4, fallbackLastUpdated)
		ipv4 = fallbackIPv4
	}
	if err6 != nil || len(ipv6) == 0 {
		log.Printf("Warning: failed to fetch Cloudflare IPv6 ranges: %v, using fallback (last updated %s)", err6, fallbackLastUpdated)
		ipv6 = fallbackIPv6
	}

	// Build config
	var b strings.Builder
	b.WriteString("# Cloudflare Real IP Restoration\n")
	b.WriteString("# Auto-generated by Proxera agent - do not edit manually\n\n")

	b.WriteString("# IPv4 ranges\n")
	for _, cidr := range ipv4 {
		fmt.Fprintf(&b, "set_real_ip_from %s;\n", cidr)
	}

	b.WriteString("\n# IPv6 ranges\n")
	for _, cidr := range ipv6 {
		fmt.Fprintf(&b, "set_real_ip_from %s;\n", cidr)
	}

	b.WriteString("\nreal_ip_header CF-Connecting-IP;\n")

	if err := os.WriteFile(cloudflareConfPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("failed to write cloudflare real IP config: %w", err)
	}

	log.Printf("Wrote Cloudflare real IP config to %s", cloudflareConfPath)
	return nil
}

func fetchIPRanges(url string) ([]string, error) {
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP %d from %s", resp.StatusCode, url)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var ranges []string
	for _, line := range strings.Split(strings.TrimSpace(string(body)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			ranges = append(ranges, line)
		}
	}
	return ranges, nil
}
