package deploy

import (
	"log"
	"os"
)

const (
	crowdsecBlocklistPath = "/etc/nginx/conf.d/crowdsec_blocklist.conf"

	crowdsecBlocklistDefault = `# CrowdSec blocklist - auto-generated by Proxera
# This file is updated automatically when CrowdSec bouncer sync is active.

geo $crowdsec_blocklist {
    default 0;
}
`
)

// EnsureCrowdSecBlocklist ensures the CrowdSec geo blocklist config exists.
// Creates a default empty blocklist if the file doesn't exist, so nginx
// doesn't fail on an undefined $crowdsec_blocklist variable.
func (d *Deployer) EnsureCrowdSecBlocklist() error {
	if _, err := os.Stat(crowdsecBlocklistPath); err == nil {
		return nil // already exists
	}

	if err := os.WriteFile(crowdsecBlocklistPath, []byte(crowdsecBlocklistDefault), 0644); err != nil {
		return err
	}

	log.Printf("Created default CrowdSec blocklist config at %s", crowdsecBlocklistPath)
	return nil
}
