package deploy

import (
	"log"
	"os"
	"time"
)

const (
	metricsLogFormatPath   = "/etc/nginx/conf.d/proxera-log-format.conf"
	metricsLogFormatMaxAge = 30 * 24 * time.Hour // Refresh after 30 days

	metricsLogFormatConfig = `# Proxera Metrics Log Format
# Auto-generated by Proxera agent - do not edit manually

log_format proxera_metrics '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '$request_time $upstream_response_time '
    '$upstream_status $upstream_cache_status '
    '$request_length $connection $connection_requests';
`
)

// EnsureMetricsLogFormat ensures the proxera_metrics log format config exists in nginx.
// Skips if the file exists and is recent enough.
func (d *Deployer) EnsureMetricsLogFormat() error {
	info, err := os.Stat(metricsLogFormatPath)
	if err == nil && time.Since(info.ModTime()) < metricsLogFormatMaxAge {
		return nil
	}

	if err := os.WriteFile(metricsLogFormatPath, []byte(metricsLogFormatConfig), 0644); err != nil {
		return err
	}

	log.Printf("Wrote proxera_metrics log format config to %s", metricsLogFormatPath)
	return nil
}
