package deploy

import (
	"log"
	"os"
	"time"
)

const (
	logrotatePath   = "/etc/logrotate.d/proxera-nginx"
	logrotateMaxAge = 30 * 24 * time.Hour

	logrotateConfig = `# Proxera nginx log rotation
# Auto-generated by Proxera agent - do not edit manually

/var/log/nginx/*_access.log
/var/log/nginx/*_error.log
/var/log/nginx/crowdsec_access.log
{
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 0644 root root
    sharedscripts
    postrotate
        invoke-rc.d nginx rotate >/dev/null 2>&1
    endscript
}
`
)

// EnsureLogRotation ensures a logrotate config exists for Proxera-managed nginx logs.
// Skips if the file exists and is recent enough.
func (d *Deployer) EnsureLogRotation() error {
	info, err := os.Stat(logrotatePath)
	if err == nil && time.Since(info.ModTime()) < logrotateMaxAge {
		return nil
	}

	if err := os.WriteFile(logrotatePath, []byte(logrotateConfig), 0644); err != nil {
		return err
	}

	log.Printf("Wrote logrotate config to %s", logrotatePath)
	return nil
}